def CountDNAnt(Genome, Pattern):
    """
    Count the number of times a pattern appears in a DNA sequence.

    Args:
        Genome (str): The DNA sequence to search within.
        Pattern (str): The DNA pattern to search for.

    Returns:
        int: The count of Pattern occurrences in Genome.
    """
    n = len(Genome)
    m = len(Pattern)
    count = 0
    for i in range(n - m + 1):
        if Genome[i:i + m] == Pattern:
            count += 1
    return count


# Example usage
Genome = "AGCTCAGAGCCGGGAACTGTTCACTCGGACACGGCCGAGTGTGGGTACTGTTTAGGCTACGAAGTTCCCAGATTCTTCCACGGAATTGCCTCTCCAGAGTCCACCTTATCTTTTTCGAGAGACTTCGGCTTTTAGCTAACTAGAAGTCTGGGTTCTGTCAGTTCCGCCTCGCAGTCAGTCGTGATAATCTACACAGGCGTCATACCAAAGAAAACATCGTGTCAAATCATCGGAACAGATCCTTGCTACTTAATGTGGGACCCGAAGTCCTCATAACCTGCTGTATCAACGGCCACCGCATTTCATCTAGCCATTAACCTATCGTCGTACATTGGGTACCTGAGGGATCACGATTGGACCGACGCCACTGGGTTCAGATTCGAGAAATGCAATCCTGGACAGCTAAATCCATTCCCCTCTTCGCCTCTTGGGTCCGGATTACATGTAAATCCGAAAGGCACGAGCCTGTCAACTCGTGACTTTGCATGTGCGCTGCGCGAAAATGTTTGGGGCGTCAGCTGTAATTAACGGCGCTTGTCACATCGAAACTGGCCACTAGGTTACCACTTCCTAGCCAAATCTACGCTGGTGGGATCGTGTAGCGTTAATTCCTAGGTGGTACGTGTGACCTGGTACGCAAAAACCCGCTACCCAACGATGCGCGAATCTAATTGTCTATGGTGGTGCCTCCGGATTATTGGTACAGGGTATAAACGAATCTTTAATGAAAGACCAAGTGCTAATACATACATGCCTCGCATAGGGGTGCGCCAGGTGTTAGTACTTCTGAAGTCGTCATAAATTATTCTGCAAGTAGAGGGTCCATGTCCAAGTAAATATGGGTTGTCCCTTGAGATTTAGCTTTGAGATCGGGAGGGGTAAGTAAGGCAGGTCCCGGTTTGGCAGTGACCAACTCGACAGAA"
Pattern = "A"
result = CountDNAnt(Genome, Pattern)
print(f"Pattern '{Pattern}' occurs {result} times.")
